# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Project Deliverables

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:  
  Task-Runner:
    runs-on: ubuntu-latest
    steps:

    - name: Check out Code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: 1 - Load SQL Data
      run: |
        python3 1_load_sql_data.py
        
    - name: 2 - Load File Data
      run: |
        python3 2_load_file_data.py

    - name: Upload Output SQLite DB
      uses: actions/upload-artifact@v4
      with:
        name: hello-heidi
        path: hello-heidi.sqlite